// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var ArcCurve, CubicBezierCurve3, QuadraticBezierCurve3, Spline, SplineCurve3, THREE, Vector2, Vector3, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  THREE = require('three');

  /**
    *All classes , functions etc defined here are simple wrappers, to make "logical" namespacing
    *easier (ie Maths.Vector2 instead of THREE.Vector2), and to add a level of indirection between api and implementation
    *
  */


  /** 
  * 3d vector class: simple wrapper around THREE.Vector3 + some additional params parsing helpers
  */


  Vector3 = (function(_super) {
    __extends(Vector3, _super);

    function Vector3(options) {
      Vector3.__super__.constructor.call(this, options);
    }

    return Vector3;

  })(THREE.Vector3);

  Vector2 = (function(_super) {
    __extends(Vector2, _super);

    function Vector2(options) {
      Vector2.__super__.constructor.call(this, options);
    }

    return Vector2;

  })(THREE.Vector2);

  SplineCurve3 = (function(_super) {
    __extends(SplineCurve3, _super);

    function SplineCurve3() {
      _ref = SplineCurve3.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return SplineCurve3;

  })(THREE.SplineCurve3);

  Spline = (function(_super) {
    __extends(Spline, _super);

    function Spline(options) {
      Spline.__super__.constructor.call(this, options);
    }

    return Spline;

  })(THREE.Spline);

  ArcCurve = (function(_super) {
    __extends(ArcCurve, _super);

    function ArcCurve() {
      _ref1 = ArcCurve.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    return ArcCurve;

  })(THREE.ArcCurve);

  CubicBezierCurve3 = (function(_super) {
    __extends(CubicBezierCurve3, _super);

    function CubicBezierCurve3() {
      _ref2 = CubicBezierCurve3.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    return CubicBezierCurve3;

  })(THREE.CubicBezierCurve3);

  QuadraticBezierCurve3 = (function(_super) {
    __extends(QuadraticBezierCurve3, _super);

    function QuadraticBezierCurve3() {
      _ref3 = QuadraticBezierCurve3.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    return QuadraticBezierCurve3;

  })(THREE.QuadraticBezierCurve3);

  module.exports = {
    Vector2: Vector2,
    Vector3: Vector3,
    Spline: Spline,
    Spline3: SplineCurve3,
    ArcCurve: ArcCurve,
    Euler: THREE.Euler,
    CubicBezierCurve3: CubicBezierCurve3,
    QuadraticBezierCurve3: QuadraticBezierCurve3
  };

}).call(this);
